foo: "value from application.yml"

app:
  quotes:
    - id: 1
      quote: 'Never, never, never give up'
      author: 'Winston Churchill'
    - id: 2
      quote: 'While there''s life, there''s hope'
      author: 'Marcus Tullius Cicero'
    - id: 3
      quote: 'Failure is success in progress'
      author: 'Anonymous'
    - id: 4
      quote: 'Success demands singleness of purpose'
      author: 'Vincent Lombardi'
    - id: 5
      quote: 'The shortest answer is doing'
      author: 'Lord Herbert'

service_version: 1.0

spring:
  cloud:
    kubernetes:
      enabled: false

# Set this service to start on a random port number that is not being
# used, this will allow us to launch multiple versions of the service
# and register them with Eureka for discovery
server:
  port: 0

eureka:
  client:
    fetch-registry: false # This service does not call any other service so no need to cache list of registered services
    register-with-eureka: true # This service should register itself in eureka
    healthcheck:
     enabled: true # use the spring boot health check status to indicate to eureka if the service is up
  instance:
    instance-id: ${spring.application.name}:${random.int} # unique id for app instances registered with eureka

# expose all the spring boot actuators good for demos.
# NEVER DO THIS in production
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
